
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: awesome-pygames
  version: '20.21.11' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Games by Al Sweigart. Manual at inventwithpython.com/pygame. # 79 char long summary
  description: |
    * flippy "A game like reversi"
    * fourinarow "Get four in a row"
    * gemgem "A tile matching puzzle"
    * inkspill "Flood the screen with pixels"
    * memorypuzzle "Test your memory"
    * pentomino "5 block Tetris"
    * simulate "Repeat the pattern"
    * slidepuzzle "Traditional slide puzzle"
    * squirrel "Eat the smaller squirrels"
    * starpusher "Sokoban"
    * tetromino "Tetris-like game"
    * tetrominoforidiots "Tetris for Idiots"
    * wormy "Snake-like game"
    * website "inventwithpython.com"

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots
  base: core18
  architectures:
    - build-on: amd64
    - build-on: i386
    - build-on: armhf
    - build-on: arm64

  plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
    gtk-3-themes:
      interface: content
      target: $SNAP/data-dir/themes
      default-provider: gtk-common-themes:gtk-3-themes
    icon-themes:
      interface: content
      target: $SNAP/data-dir/icons
      default-provider: gtk-common-themes:icon-themes
    sound-themes:
      interface: content
      target: $SNAP/data-dir/sounds
      default-provider: gtk-common-themes:sounds-themes

  layout:
    /usr/share/zenity:
      bind: $SNAP/usr/share/zenity
    /usr/share/midi/freepats:
      bind: $SNAP/usr/share/midi/freepats
    /etc/fonts:
      bind: $SNAP/etc/fonts
    /etc/timidity:
      bind: $SNAP/etc/timidity
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
      bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
    /usr/share/alsa:
      bind: $SNAP/usr/share/alsa
  
  apps:
    awesome-pygames:
      command-chain: ["snap/command-chain/alsa-launch"]
      command: usr/local/bin/launcher.sh
      environment:
        LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      extensions: [gnome-3-28]
      plugs:
        - desktop
        - desktop-legacy
        - gsettings
        - wayland
        - unity7
        - x11
        - audio-playback
        - pulseaudio
        - alsa
    
  parts:
    alsa-mixin:
      plugin: dump
      source: https://github.com/diddlesnaps/snapcraft-alsa.git
      source-subdir: snapcraft-assets
      build-packages:
        - libasound2-dev
      stage-packages:
        - libasound2
        - libasound2-plugins
        - yad

    awesome-pygames:
      after: [alsa-mixin]
      plugin: python
      python-version: python3
      source: "https://github.com/Joker2770/awesome-pygames.git"
      source-depth: 1
      source-branch: main
      source-type: git
      python-packages:
        - pygame
      stage-packages:
        - zenity
        - sensible-utils
        - try:
          - libfluidsynth1
          - libfluidsynth2
        - freepats
        - libmodplug1
        - libopusfile0
        - libpulse0
        - libsndfile1
        - libmad0
        - libportmidi0
        - libsdl2-2.0-0
        - libsdl2-image-2.0-0
        - libsdl2-mixer-2.0-0
        - libsdl2-ttf-2.0-0
        - libxss1
        - libxxf86vm1
      build-packages:
        - libsdl2-dev
        - libsdl2-image-dev
        - libsdl2-mixer-dev
        - libsdl2-ttf-dev
        - libfreetype6-dev
        - libportmidi-dev
        - libjpeg8-dev
        - python3-setuptools

    include-all:
      after: [awesome-pygames]
      plugin: dump
      source: "https://github.com/Joker2770/awesome-pygames.git"
      source-depth: 1
      source-branch: main
      source-type: git
      organize:
        "*" : usr/local/bin/
      
