
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: awesome-pygames
  version: '20.21.11' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Games by Al Sweigart. Manual at inventwithpython.com/pygame. # 79 char long summary
  description: |
    * flippy "A game like reversi"
    * fourinarow "Get four in a row"
    * gemgem "A tile matching puzzle"
    * inkspill "Flood the screen with pixels"
    * memorypuzzle "Test your memory"
    * pentomino "5 block Tetris"
    * simulate "Repeat the pattern"
    * slidepuzzle "Traditional slide puzzle"
    * squirrel "Eat the smaller squirrels"
    * starpusher "Sokoban"
    * tetromino "Tetris-like game"
    * tetrominoforidiots "Tetris for Idiots"
    * wormy "Snake-like game"
    * website "inventwithpython.com"

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots
  base: core18
  
  apps:
    awesome-pygames:
      command: launcher.sh
      plugs:
        - desktop
        - desktop-legacy
        - wayland
        - unity7
        - x11
        - audio-playback
    
  parts:
    awesome-pygames:
      plugin: python
      python-version: python3
      source: "https://github.com/Joker2770/awesome-pygames.git"
      source-depth: 1
      source-branch: main
      source-type: git
      python-packages:
        - pygame
      stage-packages:
        - zenity
      build-packages:
        - python3-pip

    include-all:
      plugin: dump
      source: "https://github.com/Joker2770/awesome-pygames.git"
      source-depth: 1
      source-branch: main
      source-type: git
      stage:
        - *.*
      prime:
        - *.*
      
